# Generated by Django 4.0.2 on 2022-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, null=True)),
                ('category_description', models.TextField(max_length=200, null=True)),
                ('subcategory_name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, null=True)),
                ('product_price', models.IntegerField(null=True)),
                ('product_description', models.TextField(max_length=200, null=True)),
                ('product_qty', models.IntegerField(null=True)),
                ('product_color', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product_status', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
