# Generated by Django 4.0.2 on 2022-03-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_desctription',
            new_name='task_description',
        ),
    ]
