# Generated by Django 4.0.2 on 2022-03-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_customer_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('od', 'od'), ('delivered', 'delivered')], max_length=50, null=True),
        ),
    ]
